# Generated by Django 5.1.5 on 2025-01-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga', models.IntegerField(default=0)),
                ('harga_coret', models.IntegerField(default=0)),
                ('deskripsi1', models.TextField()),
                ('deskripsi2', models.TextField()),
                ('informasi1', models.TextField()),
                ('informasi2', models.TextField()),
                ('informasi3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/', verbose_name='Attachment')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_produk', to='ecommerce.produk', verbose_name='Model that uses the image field')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewers', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('ratings', models.IntegerField(default=0)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_produk', to='ecommerce.produk')),
            ],
        ),
    ]
