# Generated by Django 5.1.5 on 2025-01-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
