# Generated by Django 5.1.5 on 2025-01-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_produk_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='url_file',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to='attachments/', verbose_name='Attachment'),
        ),
    ]
