# Generated by Django 5.1.5 on 2025-01-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_attachment_url_file_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
