# Generated by Django 5.1.5 on 2025-01-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_review_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='sold',
            field=models.IntegerField(default=1),
        ),
    ]
