# Generated by Django 5.1.5 on 2025-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_produk_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='carousel1',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='carousel2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='carousel3',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='info_tambahan',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
