# Generated by Django 5.1.5 on 2025-02-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_review_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='deskripsi1',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Deskripsi Atas'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='deskripsi2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Deskripsi Bawah'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='informasi1',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Main Informasi'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='informasi2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Bottom Left Informasi'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='informasi3',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Bottom Right Informasi'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tanggal',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
